apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: vwdvoscos-go 
  janus-idp.io/tekton: vwdvoscos-go
  backstage.io/kubernetes-id: vwdvoscos-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vwdvoscos-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml